spring:
  profiles:
    active: db
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${adminname}
    password: ${password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret-key:

server:
  port: 8080
